// flow-typed signature: 901d2a61c7819d8c2c28a7e89bd8ba4d
// flow-typed version: <<STUB>>/cal-heatmap_v^3.6.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cal-heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cal-heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cal-heatmap/cal-heatmap' {
  declare module.exports: any;
}

declare module 'cal-heatmap/cal-heatmap.min' {
  declare module.exports: any;
}

declare module 'cal-heatmap/cal-heatmap.source-map' {
  declare module.exports: any;
}

declare module 'cal-heatmap/Gruntfile' {
  declare module.exports: any;
}

declare module 'cal-heatmap/karma.conf' {
  declare module.exports: any;
}

declare module 'cal-heatmap/src/cal-heatmap' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/d3.min' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/destroy' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/highlight' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-auto-set-legendMargin' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-col-row-limit' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-dataType' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-domain-subDomain' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-domainLabelFormat' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-domainMargin-legendMargin' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-highlight' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-itemName' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-itemNamespace' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-itemSelector' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-subDomainDateFormat' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init-subDomainTextFormat' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/init' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/jumpto' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/next' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/previous' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/removeLegend' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/api/showLegend' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/data/getDatas' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/date/dateIsLessThan' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/date/isNow' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/date/jump' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/dst/dst' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/function' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/misc/getHighlightClassName' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/module-callback' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/module-data' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/module-domain' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/module-legend' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/painting/column-row-count' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/src/painting/global' {
  declare module.exports: any;
}

declare module 'cal-heatmap/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cal-heatmap/cal-heatmap.js' {
  declare module.exports: $Exports<'cal-heatmap/cal-heatmap'>;
}
declare module 'cal-heatmap/cal-heatmap.min.js' {
  declare module.exports: $Exports<'cal-heatmap/cal-heatmap.min'>;
}
declare module 'cal-heatmap/cal-heatmap.source-map.js' {
  declare module.exports: $Exports<'cal-heatmap/cal-heatmap.source-map'>;
}
declare module 'cal-heatmap/Gruntfile.js' {
  declare module.exports: $Exports<'cal-heatmap/Gruntfile'>;
}
declare module 'cal-heatmap/karma.conf.js' {
  declare module.exports: $Exports<'cal-heatmap/karma.conf'>;
}
declare module 'cal-heatmap/src/cal-heatmap.js' {
  declare module.exports: $Exports<'cal-heatmap/src/cal-heatmap'>;
}
declare module 'cal-heatmap/test/d3.min.js' {
  declare module.exports: $Exports<'cal-heatmap/test/d3.min'>;
}
declare module 'cal-heatmap/test/src/api/destroy.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/destroy'>;
}
declare module 'cal-heatmap/test/src/api/highlight.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/highlight'>;
}
declare module 'cal-heatmap/test/src/api/init-auto-set-legendMargin.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-auto-set-legendMargin'>;
}
declare module 'cal-heatmap/test/src/api/init-col-row-limit.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-col-row-limit'>;
}
declare module 'cal-heatmap/test/src/api/init-dataType.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-dataType'>;
}
declare module 'cal-heatmap/test/src/api/init-domain-subDomain.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-domain-subDomain'>;
}
declare module 'cal-heatmap/test/src/api/init-domainLabelFormat.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-domainLabelFormat'>;
}
declare module 'cal-heatmap/test/src/api/init-domainMargin-legendMargin.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-domainMargin-legendMargin'>;
}
declare module 'cal-heatmap/test/src/api/init-highlight.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-highlight'>;
}
declare module 'cal-heatmap/test/src/api/init-itemName.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-itemName'>;
}
declare module 'cal-heatmap/test/src/api/init-itemNamespace.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-itemNamespace'>;
}
declare module 'cal-heatmap/test/src/api/init-itemSelector.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-itemSelector'>;
}
declare module 'cal-heatmap/test/src/api/init-subDomainDateFormat.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-subDomainDateFormat'>;
}
declare module 'cal-heatmap/test/src/api/init-subDomainTextFormat.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init-subDomainTextFormat'>;
}
declare module 'cal-heatmap/test/src/api/init.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/init'>;
}
declare module 'cal-heatmap/test/src/api/jumpto.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/jumpto'>;
}
declare module 'cal-heatmap/test/src/api/next.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/next'>;
}
declare module 'cal-heatmap/test/src/api/previous.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/previous'>;
}
declare module 'cal-heatmap/test/src/api/removeLegend.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/removeLegend'>;
}
declare module 'cal-heatmap/test/src/api/showLegend.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/api/showLegend'>;
}
declare module 'cal-heatmap/test/src/data/getDatas.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/data/getDatas'>;
}
declare module 'cal-heatmap/test/src/date/dateIsLessThan.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/date/dateIsLessThan'>;
}
declare module 'cal-heatmap/test/src/date/isNow.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/date/isNow'>;
}
declare module 'cal-heatmap/test/src/date/jump.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/date/jump'>;
}
declare module 'cal-heatmap/test/src/dst/dst.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/dst/dst'>;
}
declare module 'cal-heatmap/test/src/function.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/function'>;
}
declare module 'cal-heatmap/test/src/misc/getHighlightClassName.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/misc/getHighlightClassName'>;
}
declare module 'cal-heatmap/test/src/module-callback.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/module-callback'>;
}
declare module 'cal-heatmap/test/src/module-data.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/module-data'>;
}
declare module 'cal-heatmap/test/src/module-domain.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/module-domain'>;
}
declare module 'cal-heatmap/test/src/module-legend.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/module-legend'>;
}
declare module 'cal-heatmap/test/src/painting/column-row-count.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/painting/column-row-count'>;
}
declare module 'cal-heatmap/test/src/painting/global.js' {
  declare module.exports: $Exports<'cal-heatmap/test/src/painting/global'>;
}
declare module 'cal-heatmap/test/test.js' {
  declare module.exports: $Exports<'cal-heatmap/test/test'>;
}
