// flow-typed signature: 2216554b42de301d6bd4d83ac46de023
// flow-typed version: <<STUB>>/net_v^1.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'net'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'net' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'net/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'net/index' {
  declare module.exports: $Exports<'net'>;
}
declare module 'net/index.js' {
  declare module.exports: $Exports<'net'>;
}
declare module 'net/test.js' {
  declare module.exports: $Exports<'net/test'>;
}
