// flow-typed signature: ec2e38ce951e7e891a716fc159c09924
// flow-typed version: <<STUB>>/nvd3_v^1.8.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nvd3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nvd3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nvd3/build/nv.d3' {
  declare module.exports: any;
}

declare module 'nvd3/build/nv.d3.min' {
  declare module.exports: any;
}

declare module 'nvd3/examples/lib/colorbrewer' {
  declare module.exports: any;
}

declare module 'nvd3/examples/lib/stream_layers' {
  declare module.exports: any;
}

declare module 'nvd3/GruntFile' {
  declare module.exports: any;
}

declare module 'nvd3/meteor/export' {
  declare module.exports: any;
}

declare module 'nvd3/package' {
  declare module.exports: any;
}

declare module 'nvd3/src/core' {
  declare module.exports: any;
}

declare module 'nvd3/src/dom' {
  declare module.exports: any;
}

declare module 'nvd3/src/interactiveLayer' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/axis' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/boxPlot' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/boxPlotChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/bullet' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/bulletChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/candlestickBar' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/cumulativeLineChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/discreteBar' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/discreteBarChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/distribution' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/focus' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/forceDirectedGraph' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/furiousLegend' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/historicalBar' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/historicalBarChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/legend' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/line' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/lineChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/linePlusBarChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/multiBar' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/multiBarChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/multiBarHorizontal' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/multiBarHorizontalChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/multiChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/ohlcBar' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/parallelCoordinates' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/parallelCoordinatesChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/pie' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/pieChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/scatter' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/scatterChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/sparkline' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/sparklinePlus' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/stackedArea' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/stackedAreaChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/sunburst' {
  declare module.exports: any;
}

declare module 'nvd3/src/models/sunburstChart' {
  declare module.exports: any;
}

declare module 'nvd3/src/tooltip' {
  declare module.exports: any;
}

declare module 'nvd3/src/utils' {
  declare module.exports: any;
}

declare module 'nvd3/test/node/GruntFile' {
  declare module.exports: any;
}

declare module 'nvd3/test/node/nodeTest' {
  declare module.exports: any;
}

declare module 'nvd3/test/stream_layers' {
  declare module.exports: any;
}

declare module 'nvd3/test/testScript' {
  declare module.exports: any;
}

declare module 'nvd3/test/tinytest/nv-is-defined-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nvd3/build/nv.d3.js' {
  declare module.exports: $Exports<'nvd3/build/nv.d3'>;
}
declare module 'nvd3/build/nv.d3.min.js' {
  declare module.exports: $Exports<'nvd3/build/nv.d3.min'>;
}
declare module 'nvd3/examples/lib/colorbrewer.js' {
  declare module.exports: $Exports<'nvd3/examples/lib/colorbrewer'>;
}
declare module 'nvd3/examples/lib/stream_layers.js' {
  declare module.exports: $Exports<'nvd3/examples/lib/stream_layers'>;
}
declare module 'nvd3/GruntFile.js' {
  declare module.exports: $Exports<'nvd3/GruntFile'>;
}
declare module 'nvd3/meteor/export.js' {
  declare module.exports: $Exports<'nvd3/meteor/export'>;
}
declare module 'nvd3/package.js' {
  declare module.exports: $Exports<'nvd3/package'>;
}
declare module 'nvd3/src/core.js' {
  declare module.exports: $Exports<'nvd3/src/core'>;
}
declare module 'nvd3/src/dom.js' {
  declare module.exports: $Exports<'nvd3/src/dom'>;
}
declare module 'nvd3/src/interactiveLayer.js' {
  declare module.exports: $Exports<'nvd3/src/interactiveLayer'>;
}
declare module 'nvd3/src/models/axis.js' {
  declare module.exports: $Exports<'nvd3/src/models/axis'>;
}
declare module 'nvd3/src/models/boxPlot.js' {
  declare module.exports: $Exports<'nvd3/src/models/boxPlot'>;
}
declare module 'nvd3/src/models/boxPlotChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/boxPlotChart'>;
}
declare module 'nvd3/src/models/bullet.js' {
  declare module.exports: $Exports<'nvd3/src/models/bullet'>;
}
declare module 'nvd3/src/models/bulletChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/bulletChart'>;
}
declare module 'nvd3/src/models/candlestickBar.js' {
  declare module.exports: $Exports<'nvd3/src/models/candlestickBar'>;
}
declare module 'nvd3/src/models/cumulativeLineChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/cumulativeLineChart'>;
}
declare module 'nvd3/src/models/discreteBar.js' {
  declare module.exports: $Exports<'nvd3/src/models/discreteBar'>;
}
declare module 'nvd3/src/models/discreteBarChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/discreteBarChart'>;
}
declare module 'nvd3/src/models/distribution.js' {
  declare module.exports: $Exports<'nvd3/src/models/distribution'>;
}
declare module 'nvd3/src/models/focus.js' {
  declare module.exports: $Exports<'nvd3/src/models/focus'>;
}
declare module 'nvd3/src/models/forceDirectedGraph.js' {
  declare module.exports: $Exports<'nvd3/src/models/forceDirectedGraph'>;
}
declare module 'nvd3/src/models/furiousLegend.js' {
  declare module.exports: $Exports<'nvd3/src/models/furiousLegend'>;
}
declare module 'nvd3/src/models/historicalBar.js' {
  declare module.exports: $Exports<'nvd3/src/models/historicalBar'>;
}
declare module 'nvd3/src/models/historicalBarChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/historicalBarChart'>;
}
declare module 'nvd3/src/models/legend.js' {
  declare module.exports: $Exports<'nvd3/src/models/legend'>;
}
declare module 'nvd3/src/models/line.js' {
  declare module.exports: $Exports<'nvd3/src/models/line'>;
}
declare module 'nvd3/src/models/lineChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/lineChart'>;
}
declare module 'nvd3/src/models/linePlusBarChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/linePlusBarChart'>;
}
declare module 'nvd3/src/models/multiBar.js' {
  declare module.exports: $Exports<'nvd3/src/models/multiBar'>;
}
declare module 'nvd3/src/models/multiBarChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/multiBarChart'>;
}
declare module 'nvd3/src/models/multiBarHorizontal.js' {
  declare module.exports: $Exports<'nvd3/src/models/multiBarHorizontal'>;
}
declare module 'nvd3/src/models/multiBarHorizontalChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/multiBarHorizontalChart'>;
}
declare module 'nvd3/src/models/multiChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/multiChart'>;
}
declare module 'nvd3/src/models/ohlcBar.js' {
  declare module.exports: $Exports<'nvd3/src/models/ohlcBar'>;
}
declare module 'nvd3/src/models/parallelCoordinates.js' {
  declare module.exports: $Exports<'nvd3/src/models/parallelCoordinates'>;
}
declare module 'nvd3/src/models/parallelCoordinatesChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/parallelCoordinatesChart'>;
}
declare module 'nvd3/src/models/pie.js' {
  declare module.exports: $Exports<'nvd3/src/models/pie'>;
}
declare module 'nvd3/src/models/pieChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/pieChart'>;
}
declare module 'nvd3/src/models/scatter.js' {
  declare module.exports: $Exports<'nvd3/src/models/scatter'>;
}
declare module 'nvd3/src/models/scatterChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/scatterChart'>;
}
declare module 'nvd3/src/models/sparkline.js' {
  declare module.exports: $Exports<'nvd3/src/models/sparkline'>;
}
declare module 'nvd3/src/models/sparklinePlus.js' {
  declare module.exports: $Exports<'nvd3/src/models/sparklinePlus'>;
}
declare module 'nvd3/src/models/stackedArea.js' {
  declare module.exports: $Exports<'nvd3/src/models/stackedArea'>;
}
declare module 'nvd3/src/models/stackedAreaChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/stackedAreaChart'>;
}
declare module 'nvd3/src/models/sunburst.js' {
  declare module.exports: $Exports<'nvd3/src/models/sunburst'>;
}
declare module 'nvd3/src/models/sunburstChart.js' {
  declare module.exports: $Exports<'nvd3/src/models/sunburstChart'>;
}
declare module 'nvd3/src/tooltip.js' {
  declare module.exports: $Exports<'nvd3/src/tooltip'>;
}
declare module 'nvd3/src/utils.js' {
  declare module.exports: $Exports<'nvd3/src/utils'>;
}
declare module 'nvd3/test/node/GruntFile.js' {
  declare module.exports: $Exports<'nvd3/test/node/GruntFile'>;
}
declare module 'nvd3/test/node/nodeTest.js' {
  declare module.exports: $Exports<'nvd3/test/node/nodeTest'>;
}
declare module 'nvd3/test/stream_layers.js' {
  declare module.exports: $Exports<'nvd3/test/stream_layers'>;
}
declare module 'nvd3/test/testScript.js' {
  declare module.exports: $Exports<'nvd3/test/testScript'>;
}
declare module 'nvd3/test/tinytest/nv-is-defined-test.js' {
  declare module.exports: $Exports<'nvd3/test/tinytest/nv-is-defined-test'>;
}
