// flow-typed signature: e276aa302ba2366a3c2154abc0dcb937
// flow-typed version: <<STUB>>/toolbox-loader_v0.0.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toolbox-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'toolbox-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'toolbox-loader/index' {
  declare module.exports: $Exports<'toolbox-loader'>;
}
declare module 'toolbox-loader/index.js' {
  declare module.exports: $Exports<'toolbox-loader'>;
}
